version: "3.8"

services:
  run-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000

#Para correr el docker-compose:
#docker compose -p opt-app -f docker-compose.yml up --build

